<a href="https://colab.research.google.com/github/OswalGit01/Parcial-1/blob/main/Parcial1OswalGomez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
'SECCION 1: NumPy'

'SECCION 1: NumPy'

In [66]:
# Punto 1.

import numpy as np

numeros = np.arange(1, 100)
Multiplos7 = numeros[numeros % 7 == 0]
print('Los multiplos de 7 en el array son:')
print(Multiplos7)

Los multiplos de 7 en el array son:
[ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]


In [67]:
#Punto 2

matriz1 = np.random.randint(10, 50, size=(4, 4))
print(matriz1)

matriz1[matriz1 % 2 != 0] = -1
print('Matriz con impares reemplazados por -1:')
print(matriz1)

[[31 12 13 45]
 [40 43 30 38]
 [26 22 39 30]
 [44 40 27 33]]
Matriz con impares reemplazados por -1:
[[-1 12 -1 -1]
 [40 -1 30 38]
 [26 22 -1 30]
 [44 40 -1 -1]]


In [68]:
#Punto 3

matriz2 = np.random.uniform(0, 1, size=(5, 5))
print(matriz2)

sumacolumnas = matriz2.sum(axis=0)
print('Suma por columnas:')
print(sumacolumnas)

[[0.55945667 0.94650511 0.11606876 0.39362844 0.89706536]
 [0.70630752 0.84896827 0.30929513 0.25434966 0.74037252]
 [0.50718058 0.85679873 0.03065077 0.1979904  0.11666382]
 [0.75324721 0.93777022 0.95200263 0.79210406 0.44270506]
 [0.43507344 0.39391207 0.28426975 0.67363225 0.0178339 ]]
Suma por columnas:
[2.96126542 3.98395441 1.69228704 2.3117048  2.21464066]


In [69]:
# Punto 4

arr = np.array([1, 2, 3, 4, 5])

arrinvert = arr[::-1]

print('Array:', arr)
print('Array invertido:', arrinvert)

Array: [1 2 3 4 5]
Array invertido: [5 4 3 2 1]


In [70]:
# Punto 5

MatrizIdentidad = np.eye(6)

matriz4 = (MatrizIdentidad * 3)

print('Matriz identidad 6x6:')
print(MatrizIdentidad)

print('Matriz identidad multiplicada por 3:')
print(matriz4)

#OBSERVACION: La matriz sigue un patron donde los valores que atraviesan de forma diagonal toda la matriz se repiten omuestran una secuencia sucesiva, dodne aumenta la posición hacia la decha de la columna del siguiente valor pero tambien aumenta hacia abajo en las filas,

Matriz identidad 6x6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Matriz identidad multiplicada por 3:
[[3. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3.]]


In [71]:
# Punto 6

arr1 = np.random.randint(1, 100, size=15)
arr2 = np.sort(arr1)[::-1]

print('Array original:')
print(arr1)

print('Array ordenado de mayor a menor:')
print(arr2)

Array original:
[31 55 66 13 93 10 71 16 66 94 56 62 44 19 73]
Array ordenado de mayor a menor:
[94 93 73 71 66 66 62 56 55 44 31 19 16 13 10]


In [72]:
# Punto 7

arr3 = np.random.randint(0, 100, size=30)

media1 = np.mean(arr3)
mediana1 = np.median(arr3)
desviacion1 = np.std(arr3)

print("Array de valores:")
print(arr3)

print('La media es:', media1 )
print('La mediana es:', mediana1)
print('La desviación estándar es:', desviacion1)

Array de valores:
[38 20 99 86 30 47 29 21 86 53 67 90 78 88 88 89 56 82 86 66  5 32 22 50
 33 10 52  0 20 83]
La media es: 53.53333333333333
La mediana es: 52.5
La desviación estándar es: 29.760973699722186


In [73]:
# Punto 8

matriz5 = np.random.randint(0, 100, size=(6, 3))

promfila = np.mean(matriz5, axis=1)

minim1 = np.argmin(promfila)

matriz5[minim1] = 0

print('Matriz modificada:')
print(matriz5)

print('La fila', minim1, 'tenía el menor promedio.')

Matriz modificada:
[[71 50 15]
 [69 41 85]
 [69 53 95]
 [ 1 89 61]
 [ 8 59 45]
 [ 0  0  0]]
La fila 5 tenía el menor promedio.


In [74]:
# Punto 9

arr4 = np.random.randint(1, 20, size=(3, 4))

print('Array:')
print(arr4)

cumsum1 = np.cumsum(arr4, axis=1)

print('Cumsum por filas:')
print(cumsum1)

Array:
[[12 17  4 17]
 [ 7 16  7 19]
 [15 13 12  4]]
Cumsum por filas:
[[12 29 33 50]
 [ 7 23 30 49]
 [15 28 40 44]]


In [75]:
# Punto 10

arr5 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

diagonal1 = np.diag(arr5)

print('Diagonal principal:')
print(diagonal1)

Diagonal principal:
[10 50 90]


In [76]:
'SECCION : Pandas'

'SECCION : Pandas'

In [77]:
# Datos para los siguientes puntos de esta sección.

Datos1 = {'Nombre': ['Pedro', 'Mariana', 'Andres', 'Laura', 'Felipe', 'Carlos', 'Alex'],
    'Edad':[32, 28, 45, 37, 22, 23, 30],
    'Ciudad':['Medellin', 'Bogotá', 'Bogota', 'Medellin', 'Pereira', 'Medellin', 'Medellín'],
    'Salario' :[2100000, 1800000, 3200000, 2500000, 1900000, 2100000, 1850000]}

In [78]:
# Punto 11

import pandas as pd

df1 = pd.DataFrame(Datos1)
print('df1')
print(df1)

salariofiltrado = df1[df1['Salario'] > 2000000]
print('Filtrado por salarios mayores a 2000000:')
print(salariofiltrado)

df1
    Nombre  Edad    Ciudad  Salario
0    Pedro    32  Medellin  2100000
1  Mariana    28    Bogotá  1800000
2   Andres    45    Bogota  3200000
3    Laura    37  Medellin  2500000
4   Felipe    22   Pereira  1900000
5   Carlos    23  Medellin  2100000
6     Alex    30  Medellín  1850000
Filtrado por salarios mayores a 2000000:
   Nombre  Edad    Ciudad  Salario
0   Pedro    32  Medellin  2100000
2  Andres    45    Bogota  3200000
3   Laura    37  Medellin  2500000
5  Carlos    23  Medellin  2100000


In [79]:
# Punto 12

df2 = pd.read_csv("DBPARCIAL1.csv")
print('Dataframe')
print(df2)


Dataframe
     vigencia nombre_comuna_o_corregimiento rango_edades  genero_masculino  \
0        2020                      COMUNA 1        00-04               796   
1        2020                      COMUNA 1        05-09               801   
2        2020                      COMUNA 1        10-14               830   
3        2020                      COMUNA 1        15-19               917   
4        2020                      COMUNA 1        20-24               989   
..        ...                           ...          ...               ...   
289      2020                  LAS MARCADAS        80-84                24   
290      2020                  LAS MARCADAS        85-89                13   
291      2020                  LAS MARCADAS        90-94                 6   
292      2020                  LAS MARCADAS        95-99                 3   
293      2020                  LAS MARCADAS    100 o mas                 1   

     genero_femenino  poblacion_estimada_global  
0  

In [80]:
df2.head(10)

vigencia nombre_comuna_o_corregimiento rango_edades  genero_masculino  \
0      2020                      COMUNA 1        00-04               796   
1      2020                      COMUNA 1        05-09               801   
2      2020                      COMUNA 1        10-14               830   
3      2020                      COMUNA 1        15-19               917   
4      2020                      COMUNA 1        20-24               989   
5      2020                      COMUNA 1        25-29               986   
6      2020                      COMUNA 1        30-34               919   
7      2020                      COMUNA 1        35-39               907   
8      2020                      COMUNA 1        40-44               813   
9      2020                      COMUNA 1        45-49               724   

   genero_femenino  poblacion_estimada_global  
0              790                       1586  
1              778                       1579  
2              803                       1633  
3              916                       1833  
4             1039                       2028  
5             1103                       2089  
6             1047                       1966  
7             1026                       1933  
8              924                       1737  
9              852                       1576

In [81]:
df2.tail(5)

vigencia nombre_comuna_o_corregimiento rango_edades  genero_masculino  \
289      2020                  LAS MARCADAS        80-84                24   
290      2020                  LAS MARCADAS        85-89                13   
291      2020                  LAS MARCADAS        90-94                 6   
292      2020                  LAS MARCADAS        95-99                 3   
293      2020                  LAS MARCADAS    100 o mas                 1   

     genero_femenino  poblacion_estimada_global  
289               35                         59  
290               19                         32  
291               10                         16  
292                3                          6  
293                1                          2

In [82]:
# Punto 13

datos2 = {'Fecha': ['2024-01-10', '2024-04-20', '2024-07-15', '2024-10-01', '2024-12-25']}

df3 = pd.DataFrame(datos2)

df3['Fecha'] = pd.to_datetime(df3['Fecha'])

meses = {
    1: 'Enero', 2: 'Febrero', 3: 'Marzo', 4: 'Abril',
    5: 'Mayo', 6: 'Junio', 7: 'Julio', 8: 'Agosto',
    9: 'Septiembre', 10: 'Octubre', 11: 'Noviembre', 12: 'Diciembre'}

df3['Mes'] = df3['Fecha'].dt.month.map(meses) #el .map reemplaza el valor del diccionario 'meses' luego de extraerlo de la fecha y la relaciona al nombre.

print(df3)

       Fecha        Mes
0 2024-01-10      Enero
1 2024-04-20      Abril
2 2024-07-15      Julio
3 2024-10-01    Octubre
4 2024-12-25  Diciembre


In [83]:
# Datos para los siguientes puntos de esta sección.

Datos1 = {'Nombre': ['Pedro', 'Mariana', 'Andres', 'Laura', 'Felipe', 'Carlos', 'Alex'],
    'Edad':[32, 28, 45, 37, 22, 23, 30],
    'Ciudad':['Medellin', 'Bogotá', 'Bogota', 'Medellin', 'Pereira', 'Medellin', 'Medellín'],
    'Salario' :[2100000, 1800000, 3200000, 2500000, 1900000, 2100000, 1850000]}

In [84]:
# Punto 14

df4 = pd.DataFrame(Datos1)

salarioprom = df4.groupby('Ciudad')['Salario'].mean().astype(int)

print('Salario promedio por ciudad:')
print(salarioprom)

Salario promedio por ciudad:
Ciudad
Bogota      3200000
Bogotá      1800000
Medellin    2233333
Medellín    1850000
Pereira     1900000
Name: Salario, dtype: int64


In [85]:
# Punto 15

df5 = pd.DataFrame(Datos1)

df5 ['Menor de 30'] = df5['Edad'] < 30

print(df5)

    Nombre  Edad    Ciudad  Salario  Menor de 30
0    Pedro    32  Medellin  2100000        False
1  Mariana    28    Bogotá  1800000         True
2   Andres    45    Bogota  3200000        False
3    Laura    37  Medellin  2500000        False
4   Felipe    22   Pereira  1900000         True
5   Carlos    23  Medellin  2100000         True
6     Alex    30  Medellín  1850000        False


In [86]:
# Punto 16

Datos2 = { 'Salarios' : ['1950000', '2100000', '1600000', '1800000', '2000000', '1920000', 'Null', '1800000', 'Null' ],
          'Nombre' : ['Pedro', 'Mariana', 'Andres', 'Laura', 'Felipe', 'Carlos', 'Alex', 'Sebastian', 'Felix']}

df6 = pd.DataFrame(Datos2)

df6.replace('Null', pd.NA, inplace=True)

df6['Salarios'] = pd.to_numeric(df6['Salarios'], errors='coerce')

print('valores nulos en "Salarios"')
print(df6['Salarios'].isna())

df6['Salario nulo'] = df6['Salarios'].isna()

print('DataFrame final')
print(df6)

df6['Salarios'] = pd.to_numeric(df6['Salarios'], errors='coerce')

salarioprom = df6['Salarios'].mean()
print('El salario promedio es:', salarioprom)

df6['Salario ajustado'] = df6['Salarios'].fillna(salarioprom)
print(df6)

valores nulos en "Salarios"
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8     True
Name: Salarios, dtype: bool
DataFrame final
    Salarios     Nombre  Salario nulo
0  1950000.0      Pedro         False
1  2100000.0    Mariana         False
2  1600000.0     Andres         False
3  1800000.0      Laura         False
4  2000000.0     Felipe         False
5  1920000.0     Carlos         False
6        NaN       Alex          True
7  1800000.0  Sebastian         False
8        NaN      Felix          True
El salario promedio es: 1881428.5714285714
    Salarios     Nombre  Salario nulo  Salario ajustado
0  1950000.0      Pedro         False      1.950000e+06
1  2100000.0    Mariana         False      2.100000e+06
2  1600000.0     Andres         False      1.600000e+06
3  1800000.0      Laura         False      1.800000e+06
4  2000000.0     Felipe         False      2.000000e+06
5  1920000.0     Carlos         False      1.920000e+06
6        NaN  

In [87]:
# Punto 17

df7 = pd.DataFrame([
    ['Ana', 25, 'Bogotá', 25, 'Ana'],
    ['Luis', 30, 'Medellín', 30, 'Luis'],
    ['Carlos', 22, 'Cali', 22, 'Carlos']], columns=['Nombre', 'Edad', 'Ciudad', 'Edad', 'Nombre'])

print('DataFrame con columnas duplicadas:')
print(df7)

DataframeCorregido = df7.loc[:, ~df7.columns.duplicated()]

print('DataFrame sin columnas duplicadas:')
print(DataframeCorregido)


DataFrame con columnas duplicadas:
   Nombre  Edad    Ciudad  Edad  Nombre
0     Ana    25    Bogotá    25     Ana
1    Luis    30  Medellín    30    Luis
2  Carlos    22      Cali    22  Carlos
DataFrame sin columnas duplicadas:
   Nombre  Edad    Ciudad
0     Ana    25    Bogotá
1    Luis    30  Medellín
2  Carlos    22      Cali


In [88]:
# Punto 18

df8 = pd.DataFrame([
    ['Ana', 25, 'Bogotá'],
    ['Luis', 30, 'Medellín'],
    ['Carlos', 22, 'Cali']], columns=['Nombre', 'Edad', 'Ciudad'])

print(df8)

dfordenado = df8.sort_values(by=['Ciudad', 'Edad'], ascending=[True, False])

print("DataFrame ordenado:")
print(dfordenado)

   Nombre  Edad    Ciudad
0     Ana    25    Bogotá
1    Luis    30  Medellín
2  Carlos    22      Cali
DataFrame ordenado:
   Nombre  Edad    Ciudad
0     Ana    25    Bogotá
2  Carlos    22      Cali
1    Luis    30  Medellín


In [89]:
'SECCION :  Preguntas complejas'

'SECCION :  Preguntas complejas'

In [90]:
# Punto 19

df9 = pd.DataFrame({
'Producto': ['A', 'B', 'A', 'C', 'B', 'A'],
'Precio': [1200, 1500, 1300, 1000, 1600, 1250],
'Cantidad': [3, 2, 5, 1, 2, 4]
})

df9['Ingreso'] = df9['Precio'] * df9['Cantidad']

ingresototal = df9.groupby('Producto')['Ingreso'].sum()

ingresoordenado = ingresototal.sort_values(ascending=False)

print("Ingreso total por producto:")
print(ingresoordenado)

Ingreso total por producto:
Producto
A    15100
B     6200
C     1000
Name: Ingreso, dtype: int64


In [91]:
# Punto 20

import pandas as pd
import numpy as np

productos = ['Laptop', 'Tablet', 'Teléfono', 'Monitor', 'Impresora']
zonas = ['Norte', 'Sur', 'Este', 'Oeste']

df10 = pd.DataFrame({
    'fecha': pd.to_datetime(np.random.choice(pd.date_range(start='2024-01-01', end='2024-03-31'), 1000)),
    'producto': np.random.choice(productos, 1000),
    'cantidad': np.random.randint(1, 11, 1000),
    'precio_unitario': np.random.randint(100000, 300001, 1000),
    'zona': np.random.choice(zonas, 1000)})

df10['ingreso'] = df10['cantidad'] * df10['precio_unitario']

# ¿Cuál es el producto más vendido por zona?

ventasxzona = df10.groupby(['zona', 'producto'])['cantidad'].sum().reset_index()

productotopzona = ventasxzona.sort_values(['zona', 'cantidad'], ascending=[True, False]).groupby('zona').first()

print("Producto más vendido por zona:")
print(productotopzona)

# ¿Qué día del mes se obtienen más ingresos?

df10['diames'] = df10['fecha'].dt.day

ingresoxdia = df10.groupby('diames')['ingreso'].sum().sort_values(ascending=False)

print("Ingreso total por día del mes:")
print(ingresoxdia)

print("El día del mes con más ingresos es el día:"),
print(ingresoxdia.idxmax())

Producto más vendido por zona:
        producto  cantidad
zona                      
Este   Impresora       279
Norte  Impresora       331
Oeste   Teléfono       339
Sur       Laptop       415
Ingreso total por día del mes:
diames
6     52044627
5     49554170
1     46871813
11    46125059
21    43649528
18    41830285
4     41589077
8     41353337
17    41334105
28    37744639
2     37599176
10    36327130
19    36174688
14    35131713
15    34427374
7     34334307
22    33107459
3     33024963
29    32455796
12    32390118
26    31829708
23    31581817
13    31434993
24    31087546
20    29826934
25    29071940
16    27273510
31    27259230
9     26718019
27    20018713
30    19295744
Name: ingreso, dtype: int64
El día del mes con más ingresos es el día:
6
